export const seedUsers = [
  {
    customId: "usr_stu_1",
    name: "Aarav Sharma",
    email: "aarav.sharma@college.edu",
    password: "password123", // Will be hashed by pre-save or in seed
    role: "student",
    department: "Computer Science & Engineering",
    year: "3rd Year",
    rollNumber: "CSE2023089",
    phone: "+91 98765 43210",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    bio: "Passionate about full-stack web development, AI hackathons, and open source.",
  },
  {
    customId: "usr_org_1",
    name: "Dr. Rajesh Verma",
    email: "rajesh.verma@college.edu",
    password: "password123",
    role: "organizer",
    department: "Information Technology & Student Affairs",
    roleTitle: "Lead Faculty Convener",
    phone: "+91 94567 89012",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    bio: "Chief Coordinator for College Cultural & Technical Festivals with 12+ years experience in campus event orchestration.",
  },
  {
    customId: "usr_vol_1",
    name: "Rohan Gupta",
    email: "rohan.gupta@college.edu",
    password: "password123",
    role: "volunteer",
    department: "Electronics & Communication",
    year: "2nd Year",
    phone: "+91 91234 56789",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    skills: ["Stage Management", "Audio/Visual Tech", "Registration Desk", "Crowd Control"],
    availability: "Weekdays & Weekends (Full Day)",
    assignedEvents: ["TechFest 2026", "CodeSprint National Hackathon", "AI Innovation & LLM Masterclass"],
    bio: "Active NSS member and tech enthusiast. Loves coordinating hospitality and tech operations during college fests.",
  },
];

export const seedEvents = [
  {
    customId: "evt-101",
    title: "TechFest 2026: Apex Tech Expo",
    category: "Technical",
    description: "The premier annual technical symposium bringing together over 2,000 students across 40+ colleges. Features project displays, robotics arenas, tech keynotes, and competitive coding leagues.",
    banner: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80",
    date: "2026-11-15",
    endDate: "2026-11-16",
    startTime: "09:00 AM",
    endTime: "05:30 PM",
    venue: "Main Auditorium & CS Block",
    organizer: "Dept. of Computer Science & ACM Student Chapter",
    organizerContact: "techfest@college.edu",
    maxParticipants: 500,
    registeredCount: 384,
    deadline: "2026-11-10",
    status: "Published",
    isFeatured: true,
    tags: ["Robotics", "Web3", "AI", "Competitions"],
    about: "TechFest 2026 provides a platform to showcase emerging student innovations, interact with silicon valley leaders, and participate in cash-prize challenges.",
    requirements: "Valid College Student ID card, Laptop with charger for coding challenges.",
    rules: [
      "Teams can comprise 1 to 4 members.",
      "All submissions must be original work created during the designated period.",
      "Badges must be worn at all times inside the campus premises."
    ]
  },
  {
    customId: "evt-102",
    title: "CodeSprint National Hackathon",
    category: "Hackathon",
    description: "A 24-hour intense hackathon aimed at building sustainable solutions for smart campus energy, healthcare accessibility, and community disaster readiness.",
    banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80",
    date: "2026-11-22",
    endDate: "2026-11-23",
    startTime: "10:00 AM",
    endTime: "10:00 AM (Next Day)",
    venue: "Innovation Lab & Computing Center",
    organizer: "Innovation & Entrepreneurship Cell (IEDC)",
    organizerContact: "hackathon@college.edu",
    maxParticipants: 200,
    registeredCount: 192,
    deadline: "2026-11-18",
    status: "Published",
    isFeatured: true,
    tags: ["24-Hour", "Coding", "Mentorship", "Cash Prize"],
    about: "Build fast, break barriers, and pitch before venture capitalists and top engineering architects.",
    requirements: "Bring own laptops, hardware kits if participating in IoT track.",
    rules: [
      "24 hours continuous coding with periodic mentor checkpoints.",
      "Plagiarism checks will be enforced automatically on Git repositories."
    ]
  },
  {
    customId: "evt-103",
    title: "AI Innovation & LLM Masterclass",
    category: "Workshop",
    description: "Hands-on masterclass on building generative AI pipelines, fine-tuning large language models, and deploying production RAG architectures.",
    banner: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop&q=80",
    date: "2026-11-05",
    endDate: "2026-11-05",
    startTime: "01:30 PM",
    endTime: "05:00 PM",
    venue: "Seminar Hall B, 3rd Floor",
    organizer: "AI & Machine Learning Club",
    organizerContact: "aiml-club@college.edu",
    maxParticipants: 120,
    registeredCount: 120,
    deadline: "2026-11-02",
    status: "Published",
    isFeatured: true,
    tags: ["GenAI", "Python", "PyTorch", "LangChain"],
    about: "Practical hands-on workshop led by industry AI research scientists.",
    requirements: "Basic Python knowledge, Google Colab / Kaggle account setup.",
    rules: [
      "Prerequisite setup instructions must be completed before the session.",
      "Participation certificates will be provided upon assignment completion."
    ]
  },
  {
    customId: "evt-104",
    title: "Tarangini 2026: Annual Cultural Fest",
    category: "Cultural",
    description: "The biggest 3-day cultural extravaganza with battle of bands, classical dance showdown, street theater, fashion parade, and celebrity pro-nite.",
    banner: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=80",
    date: "2026-12-08",
    endDate: "2026-12-10",
    startTime: "11:00 AM",
    endTime: "10:00 PM",
    venue: "Open Air Amphitheatre & College Ground",
    organizer: "Cultural Committee & Student Council",
    organizerContact: "culturalfest@college.edu",
    maxParticipants: 1500,
    registeredCount: 940,
    deadline: "2026-12-01",
    status: "Published",
    isFeatured: true,
    tags: ["Music", "Dance", "Drama", "Celebrity Night"],
    about: "Unleash your creativity and rhythm across 25+ art, dance, and music categories.",
    requirements: "College ID card is mandatory for entry passes.",
    rules: [
      "All props and audio tracks must be submitted 24 hours prior to performance.",
      "Campus discipline guidelines must be followed strictly."
    ]
  },
  {
    customId: "evt-105",
    title: "Khelotsav: Inter-College Sports Championship",
    category: "Sports",
    description: "Annual multi-sport tournament featuring Football, Basketball, Badminton, Cricket, Table Tennis, and 4x100m Athletic relays.",
    banner: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=80",
    date: "2026-12-18",
    endDate: "2026-12-20",
    startTime: "08:00 AM",
    endTime: "06:00 PM",
    venue: "College Sports Complex & Main Ground",
    organizer: "Physical Education Department",
    organizerContact: "sports@college.edu",
    maxParticipants: 400,
    registeredCount: 260,
    deadline: "2026-12-12",
    status: "Published",
    isFeatured: false,
    tags: ["Football", "Cricket", "Basketball", "Athletics"],
    about: "Compete against the best college athletes in state-level sanctioned matches.",
    requirements: "Proper sports gear and medical fitness self-declaration.",
    rules: [
      "Standard national federation rules apply for all sport categories.",
      "Referees' decisions will be final and binding."
    ]
  },
  {
    customId: "evt-106",
    title: "Modern Full-Stack Web Development Bootcamp",
    category: "Workshop",
    description: "Complete zero-to-hero intensive hands-on lab on Next.js 15, Tailwind CSS, TypeScript, Server Actions, and Cloudflare Workers deployment.",
    banner: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80",
    date: "2026-11-28",
    endDate: "2026-11-28",
    startTime: "10:00 AM",
    endTime: "04:30 PM",
    venue: "Computer Science Lab 4",
    organizer: "Web Development Club & IEEE",
    organizerContact: "webdev@college.edu",
    maxParticipants: 80,
    registeredCount: 74,
    deadline: "2026-11-25",
    status: "Published",
    isFeatured: false,
    tags: ["React", "Next.js", "Tailwind", "FullStack"],
    about: "Build real-world SaaS applications with authentication, databases, and microservices.",
    requirements: "Node.js installed on personal laptops, GitHub profile.",
    rules: [
      "Attendance in both morning and afternoon sessions is mandatory for badge."
    ]
  },
  {
    customId: "evt-107",
    title: "Drishti: National Campus Photography Contest",
    category: "Cultural",
    description: "Showcase the essence of campus life, architectural heritage, and candid moments through your lens. Top photos displayed in the Annual Art Gallery.",
    banner: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop&q=80",
    date: "2026-11-19",
    endDate: "2026-11-19",
    startTime: "10:00 AM",
    endTime: "02:00 PM",
    venue: "Central Courtyard & Art Gallery",
    organizer: "Fine Arts & Photography Club",
    organizerContact: "photography@college.edu",
    maxParticipants: 100,
    registeredCount: 65,
    deadline: "2026-11-17",
    status: "Draft",
    isFeatured: false,
    tags: ["Photography", "Creative", "Exhibition", "Art"],
    about: "Judged by renowned documentary photographers with cash awards and gallery showcase.",
    requirements: "DSLR, Mirrorless, or High-Resolution Mobile Camera.",
    rules: [
      "Raw files must be provided upon request for authenticity check.",
      "Minimal color correction is permitted; excessive AI generation is disqualified."
    ]
  },
  {
    customId: "evt-108",
    title: "CyberShield: Ethical Hacking & Security Conclave",
    category: "Seminar",
    description: "Interactive security symposium covering vulnerability research, bug bounty hunting, zero-day analysis, and defense strategies.",
    banner: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop&q=80",
    date: "2026-12-03",
    endDate: "2026-12-03",
    startTime: "09:30 AM",
    endTime: "03:30 PM",
    venue: "Main Auditorium",
    organizer: "Cyber Security Research Group",
    organizerContact: "infosec@college.edu",
    maxParticipants: 350,
    registeredCount: 310,
    deadline: "2026-11-30",
    status: "Published",
    isFeatured: false,
    tags: ["CyberSecurity", "EthicalHacking", "CTF", "Seminar"],
    about: "Learn ethical hacking methodologies directly from certified penetration testers.",
    requirements: "Basic networking fundamentals.",
    rules: [
      "Live demonstrations will be conducted only within isolated laboratory sandboxes."
    ]
  }
];

export const seedParticipants = [
  {
    customId: "part-1",
    name: "Aarav Sharma",
    email: "aarav.sharma@college.edu",
    department: "Computer Science",
    year: "3rd Year",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    registrationDate: "2026-10-12",
    status: "Confirmed",
    ticketNumber: "TF26-8819",
    phone: "+91 98765 43210"
  },
  {
    customId: "part-2",
    name: "Aarav Sharma",
    email: "aarav.sharma@college.edu",
    department: "Computer Science",
    year: "3rd Year",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    registrationDate: "2026-10-14",
    status: "Confirmed",
    ticketNumber: "CS26-4421",
    phone: "+91 98765 43210"
  },
  {
    customId: "part-3",
    name: "Aarav Sharma",
    email: "aarav.sharma@college.edu",
    department: "Computer Science",
    year: "3rd Year",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    registrationDate: "2026-10-08",
    status: "Confirmed",
    ticketNumber: "AI26-1209",
    phone: "+91 98765 43210"
  },
  {
    customId: "part-4",
    name: "Ananya Iyer",
    email: "ananya.iyer@college.edu",
    department: "Information Technology",
    year: "2nd Year",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    registrationDate: "2026-10-15",
    status: "Confirmed",
    ticketNumber: "TF26-9012",
    phone: "+91 98234 56781"
  },
  {
    customId: "part-5",
    name: "Vikram Malhotra",
    email: "vikram.m@college.edu",
    department: "Mechanical Engineering",
    year: "4th Year",
    eventId: "evt-105",
    eventName: "Khelotsav: Inter-College Sports Championship",
    registrationDate: "2026-10-16",
    status: "Confirmed",
    ticketNumber: "KH26-3021",
    phone: "+91 97123 45678"
  },
  {
    customId: "part-6",
    name: "Sneha Reddy",
    email: "sneha.reddy@college.edu",
    department: "Electronics & Communication",
    year: "3rd Year",
    eventId: "evt-104",
    eventName: "Tarangini 2026: Annual Cultural Fest",
    registrationDate: "2026-10-17",
    status: "Pending",
    ticketNumber: "TR26-5510",
    phone: "+91 96321 89012"
  },
  {
    customId: "part-7",
    name: "Devendra Patil",
    email: "devendra.p@college.edu",
    department: "Civil Engineering",
    year: "3rd Year",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    registrationDate: "2026-10-18",
    status: "Confirmed",
    ticketNumber: "CS26-7890",
    phone: "+91 95432 10987"
  },
  {
    customId: "part-8",
    name: "Pooja Hegde",
    email: "pooja.hegde@college.edu",
    department: "Biotechnology",
    year: "1st Year",
    eventId: "evt-107",
    eventName: "Drishti: National Campus Photography Contest",
    registrationDate: "2026-10-19",
    status: "Pending",
    ticketNumber: "DR26-1144",
    phone: "+91 94123 67890"
  },
  {
    customId: "part-9",
    name: "Karan Johar Sharma",
    email: "karan.js@college.edu",
    department: "Computer Science",
    year: "4th Year",
    eventId: "evt-108",
    eventName: "CyberShield: Ethical Hacking & Security Conclave",
    registrationDate: "2026-10-19",
    status: "Confirmed",
    ticketNumber: "CY26-8921",
    phone: "+91 93214 56789"
  },
  {
    customId: "part-10",
    name: "Meera Nambiar",
    email: "meera.n@college.edu",
    department: "Electrical Engineering",
    year: "2nd Year",
    eventId: "evt-104",
    eventName: "Tarangini 2026: Annual Cultural Fest",
    registrationDate: "2026-10-20",
    status: "Confirmed",
    ticketNumber: "TR26-9041",
    phone: "+91 92345 67891"
  },
  {
    customId: "part-11",
    name: "Aditya Roy",
    email: "aditya.roy@college.edu",
    department: "Computer Science",
    year: "2nd Year",
    eventId: "evt-106",
    eventName: "Modern Full-Stack Web Development Bootcamp",
    registrationDate: "2026-10-21",
    status: "Confirmed",
    ticketNumber: "WB26-3390",
    phone: "+91 91456 78902"
  },
  {
    customId: "part-12",
    name: "Tanvi Deshmukh",
    email: "tanvi.d@college.edu",
    department: "Management Studies",
    year: "1st Year",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    registrationDate: "2026-10-22",
    status: "Cancelled",
    ticketNumber: "TF26-0045",
    phone: "+91 90567 89013"
  },
  {
    customId: "part-13",
    name: "Rishi Kapoor",
    email: "rishi.k@college.edu",
    department: "Information Technology",
    year: "3rd Year",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    registrationDate: "2026-10-22",
    status: "Confirmed",
    ticketNumber: "AI26-4481",
    phone: "+91 89678 90124"
  },
  {
    customId: "part-14",
    name: "Shreya Ghoshal",
    email: "shreya.g@college.edu",
    department: "Computer Science",
    year: "4th Year",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    registrationDate: "2026-10-23",
    status: "Confirmed",
    ticketNumber: "CS26-1234",
    phone: "+91 88789 01235"
  },
  {
    customId: "part-15",
    name: "Nikhil Chawla",
    email: "nikhil.c@college.edu",
    department: "Mechanical Engineering",
    year: "2nd Year",
    eventId: "evt-105",
    eventName: "Khelotsav: Inter-College Sports Championship",
    registrationDate: "2026-10-24",
    status: "Confirmed",
    ticketNumber: "KH26-7788",
    phone: "+91 87890 12346"
  }
];

export const seedVolunteers = [
  {
    customId: "vol-1",
    name: "Rohan Gupta",
    email: "rohan.gupta@college.edu",
    department: "Electronics & Communication",
    year: "2nd Year",
    phone: "+91 91234 56789",
    assignedEvents: ["TechFest 2026", "CodeSprint National Hackathon"],
    assignedTasksCount: 4,
    completedTasksCount: 2,
    availability: "Full Time (Morning & Evening)",
    status: "Active",
    skills: ["Stage Setup", "Hospitality", "AV Desk"]
  },
  {
    customId: "vol-2",
    name: "Priyanka Nair",
    email: "priyanka.nair@college.edu",
    department: "Computer Science",
    year: "3rd Year",
    phone: "+91 98112 23344",
    assignedEvents: ["TechFest 2026", "AI Innovation & LLM Masterclass"],
    assignedTasksCount: 3,
    completedTasksCount: 3,
    availability: "Weekdays (After 1 PM)",
    status: "Active",
    skills: ["Registration Desk", "Social Media", "Anchoring"]
  },
  {
    customId: "vol-3",
    name: "Siddharth Joshi",
    email: "siddharth.j@college.edu",
    department: "Information Technology",
    year: "2nd Year",
    phone: "+91 97223 34455",
    assignedEvents: ["CodeSprint National Hackathon"],
    assignedTasksCount: 3,
    completedTasksCount: 1,
    availability: "Full Day (Hackathon overnight shift)",
    status: "Active",
    skills: ["Network / Wi-Fi Support", "Hardware Lab", "Logistics"]
  },
  {
    customId: "vol-4",
    name: "Kavya Menon",
    email: "kavya.menon@college.edu",
    department: "Biotechnology",
    year: "3rd Year",
    phone: "+91 96334 45566",
    assignedEvents: ["Tarangini 2026: Annual Cultural Fest"],
    assignedTasksCount: 5,
    completedTasksCount: 2,
    availability: "Flexible hours",
    status: "Active",
    skills: ["Artist Hospitality", "Backstage Coordination", "Security"]
  },
  {
    customId: "vol-5",
    name: "Harsh Vardhan",
    email: "harsh.v@college.edu",
    department: "Mechanical Engineering",
    year: "4th Year",
    phone: "+91 95445 56677",
    assignedEvents: ["Khelotsav: Inter-College Sports Championship"],
    assignedTasksCount: 2,
    completedTasksCount: 1,
    availability: "Early Morning (6 AM - 2 PM)",
    status: "Approved",
    skills: ["Referee Assistance", "First Aid", "Equipment Setup"]
  },
  {
    customId: "vol-6",
    name: "Deepika Padukone Singh",
    email: "deepika.ps@college.edu",
    department: "Civil Engineering",
    year: "2nd Year",
    phone: "+91 94556 67788",
    assignedEvents: ["TechFest 2026: Apex Tech Expo"],
    assignedTasksCount: 1,
    completedTasksCount: 0,
    availability: "Weekends Only",
    status: "Pending",
    skills: ["Helpdesk", "Certificate Distribution", "Ushering"]
  },
  {
    customId: "vol-7",
    name: "Manish Sisodia",
    email: "manish.s@college.edu",
    department: "Electrical Engineering",
    year: "1st Year",
    phone: "+91 93667 78899",
    assignedEvents: ["CyberShield: Ethical Hacking & Security Conclave"],
    assignedTasksCount: 2,
    completedTasksCount: 1,
    availability: "Afternoons (12 PM - 5 PM)",
    status: "Active",
    skills: ["Badge Printing", "Mic Coordination", "Refreshments"]
  },
  {
    customId: "vol-8",
    name: "Zoya Akhtar",
    email: "zoya.akhtar@college.edu",
    department: "Management Studies",
    year: "2nd Year",
    phone: "+91 92778 89900",
    assignedEvents: ["Tarangini 2026: Annual Cultural Fest"],
    assignedTasksCount: 0,
    completedTasksCount: 0,
    availability: "Full Day",
    status: "Rejected",
    skills: ["Sponsorship desk", "VIP escort"]
  }
];

export const seedTasks = [
  {
    customId: "tsk-1",
    title: "Setup Main Stage Projectors & Sound System",
    description: "Coordinate with AV technicians to test dual HDMI inputs, wireless lapel mics, and live recording rig in Main Auditorium.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    assignedVolunteerName: "Rohan Gupta",
    priority: "Urgent",
    deadline: "2026-11-14 06:00 PM",
    status: "In Progress"
  },
  {
    customId: "tsk-2",
    title: "Verify Guest Speaker Accommodation & Mementoes",
    description: "Ensure guest kits, badges, and keynote presentation slides are loaded onto the podium laptop.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    assignedVolunteerName: "Rohan Gupta",
    priority: "High",
    deadline: "2026-11-15 08:30 AM",
    status: "Pending"
  },
  {
    customId: "tsk-3",
    title: "Manage Live Registration & QR Check-in Counter A",
    description: "Scan attendee QR codes, verify college IDs, and distribute welcome kits and food coupons.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    assignedVolunteerName: "Priyanka Nair",
    priority: "High",
    deadline: "2026-11-15 08:00 AM",
    status: "Completed"
  },
  {
    customId: "tsk-4",
    title: "Configure High-Speed Gigabit Switch in Hackathon Arena",
    description: "Install 24-port switches and configure dedicated SSIDs with 500Mbps bandwidth for all 50 hackathon teams.",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    assignedVolunteerName: "Siddharth Joshi",
    priority: "Urgent",
    deadline: "2026-11-21 08:00 PM",
    status: "Pending"
  },
  {
    customId: "tsk-5",
    title: "Midnight Snacks & Energy Drink Distribution",
    description: "Coordinate with catering team to serve pizza, sandwiches, and coffee to all hackathon teams at 1:00 AM.",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    assignedVolunteerName: "Rohan Gupta",
    priority: "Medium",
    deadline: "2026-11-23 01:00 AM",
    status: "Pending"
  },
  {
    customId: "tsk-6",
    title: "Set up Google Colab GPU Environment Accounts",
    description: "Send out pre-configured notebook credentials and API keys to 120 workshop participants.",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    assignedVolunteerName: "Priyanka Nair",
    priority: "Medium",
    deadline: "2026-11-04 04:00 PM",
    status: "Completed"
  },
  {
    customId: "tsk-7",
    title: "Collect Workshop Feedback & Trigger Digital Certificates",
    description: "Share the Google Form feedback link and verify attendance records for certificate auto-generation.",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    assignedVolunteerName: "Priyanka Nair",
    priority: "Low",
    deadline: "2026-11-05 06:00 PM",
    status: "Completed"
  },
  {
    customId: "tsk-8",
    title: "Backstage Green Room Hospitality for Bands",
    description: "Ensure green rooms are stocked with water, refreshments, mirrors, and security personnel.",
    eventId: "evt-104",
    eventName: "Tarangini 2026 Cultural Fest",
    assignedVolunteerName: "Kavya Menon",
    priority: "High",
    deadline: "2026-12-08 02:00 PM",
    status: "Pending"
  },
  {
    customId: "tsk-9",
    title: "Crowd Barrier Inspection at Open Amphitheatre",
    description: "Verify security barricading between the general student zone and stage perimeter.",
    eventId: "evt-104",
    eventName: "Tarangini 2026 Cultural Fest",
    assignedVolunteerName: "Kavya Menon",
    priority: "Urgent",
    deadline: "2026-12-08 04:00 PM",
    status: "In Progress"
  },
  {
    customId: "tsk-10",
    title: "Prepare Ground Markings & Goalpost Nets",
    description: "Mark football and basketball court lines according to official tournament regulations.",
    eventId: "evt-105",
    eventName: "Khelotsav Sports Championship",
    assignedVolunteerName: "Harsh Vardhan",
    priority: "High",
    deadline: "2026-12-17 05:00 PM",
    status: "Completed"
  },
  {
    customId: "tsk-11",
    title: "First Aid Kit & Ice Pack Station Management",
    description: "Coordinate with campus medical dispensary nurse and set up pitch-side medical booths.",
    eventId: "evt-105",
    eventName: "Khelotsav Sports Championship",
    assignedVolunteerName: "Harsh Vardhan",
    priority: "Urgent",
    deadline: "2026-12-18 07:30 AM",
    status: "In Progress"
  },
  {
    customId: "tsk-12",
    title: "Clone Starter GitHub Repos on 80 Lab Terminals",
    description: "Ensure Node.js v20, VS Code, and Vite templates are installed and verified across all Lab 4 computers.",
    eventId: "evt-106",
    eventName: "Full-Stack Bootcamp",
    assignedVolunteerName: "Siddharth Joshi",
    priority: "High",
    deadline: "2026-11-27 06:00 PM",
    status: "Completed"
  },
  {
    customId: "tsk-13",
    title: "Hang Photo Mounts & Spotlight Tuning in Art Gallery",
    description: "Mount 50 shortlisted student photographs on foam-boards with numbered caption placards.",
    eventId: "evt-107",
    eventName: "Drishti Photography Contest",
    assignedVolunteerName: "Deepika Padukone Singh",
    priority: "Low",
    deadline: "2026-11-18 05:00 PM",
    status: "Pending"
  },
  {
    customId: "tsk-14",
    title: "Security Sandbox Firewall Setup for CTF Challenge",
    description: "Isolate the hacking lab subnet to prevent unintentional traffic to campus enterprise servers.",
    eventId: "evt-108",
    eventName: "CyberShield Conclave",
    assignedVolunteerName: "Manish Sisodia",
    priority: "Urgent",
    deadline: "2026-12-02 07:00 PM",
    status: "Completed"
  },
  {
    customId: "tsk-15",
    title: "Distribute Trophy & Certificates on Podium",
    description: "Arrange trophies, medal ribbons, and cash envelopes in order of announcer cue cards.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    assignedVolunteerName: "Rohan Gupta",
    priority: "Medium",
    deadline: "2026-11-16 04:00 PM",
    status: "Pending"
  }
];

export const seedSchedules = [
  {
    customId: "sch-1",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "Inauguration & Lighting of the Lamp",
    date: "2026-11-15",
    startTime: "09:00 AM",
    endTime: "09:45 AM",
    venue: "Main Auditorium",
    coordinator: "Dr. Rajesh Verma",
    description: "Welcome address by Dean Academics and Chief Guest keynote."
  },
  {
    customId: "sch-2",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "Keynote: Next-Gen AI & Quantum Systems",
    date: "2026-11-15",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    venue: "Main Auditorium",
    coordinator: "Prof. Sunita Rao",
    description: "Distinguished guest lecture with interactive Q&A session."
  },
  {
    customId: "sch-3",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "RoboWars: Arena Battle Prelims",
    date: "2026-11-15",
    startTime: "11:45 AM",
    endTime: "01:15 PM",
    venue: "Robotics Arena (CS Quadrangle)",
    coordinator: "Rohan Gupta (Volunteer Lead)",
    description: "15kg and 30kg combat robot knockout tournament."
  },
  {
    customId: "sch-4",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "Networking Lunch & Poster Presentation",
    date: "2026-11-15",
    startTime: "01:15 PM",
    endTime: "02:15 PM",
    venue: "Student Activity Center Cafeteria",
    coordinator: "Priyanka Nair",
    description: "Buffet lunch for registered participants and poster evaluations."
  },
  {
    customId: "sch-5",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "CodeBlitz: Rapid Competitive Coding",
    date: "2026-11-15",
    startTime: "02:30 PM",
    endTime: "04:30 PM",
    venue: "Computing Lab 1 & 2",
    coordinator: "Vikram Sengupta",
    description: "2-hour speed coding contest on algorithmic problem sets."
  },
  {
    customId: "sch-6",
    eventId: "evt-101",
    eventName: "TechFest 2026: Apex Tech Expo",
    activity: "Grand Valedictory & Prize Distribution Ceremony",
    date: "2026-11-16",
    startTime: "04:00 PM",
    endTime: "05:30 PM",
    venue: "Main Auditorium",
    coordinator: "Dr. Rajesh Verma",
    description: "Announcement of winners, awarding trophies and merit certificates."
  },
  {
    customId: "sch-7",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    activity: "Hackathon Opening & Problem Statement Release",
    date: "2026-11-22",
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    venue: "Innovation Center Ground Floor",
    coordinator: "IEDC Convener",
    description: "Revealing the 5 thematic problem statements and mentor introductions."
  },
  {
    customId: "sch-8",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    activity: "Hacking Sprint Phase 1 & First Mentor Review",
    date: "2026-11-22",
    startTime: "11:00 AM",
    endTime: "04:00 PM",
    venue: "Innovation Lab & Hub",
    coordinator: "Siddharth Joshi",
    description: "Architecture critique and design verification by industry mentors."
  },
  {
    customId: "sch-9",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    activity: "Midnight Jam & Lightning Pitch Checkpoint",
    date: "2026-11-23",
    startTime: "12:00 AM",
    endTime: "02:00 AM",
    venue: "Innovation Lab Cafeteria",
    coordinator: "Rohan Gupta",
    description: "Casual pitching round with midnight snack refreshments."
  },
  {
    customId: "sch-10",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    activity: "Final Code Freeze & Demo Judging",
    date: "2026-11-23",
    startTime: "09:00 AM",
    endTime: "11:30 AM",
    venue: "Seminar Hall A",
    coordinator: "IEDC Convener",
    description: "3-minute live prototype demos in front of VC jury panel."
  },
  {
    customId: "sch-11",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    activity: "Session 1: Transformer Foundations & Attention Mechanism",
    date: "2026-11-05",
    startTime: "01:30 PM",
    endTime: "03:00 PM",
    venue: "Seminar Hall B",
    coordinator: "Priyanka Nair",
    description: "Deep dive into model weights, self-attention, and token embeddings."
  },
  {
    customId: "sch-12",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    activity: "Session 2: Building Enterprise RAG Applications",
    date: "2026-11-05",
    startTime: "03:15 PM",
    endTime: "05:00 PM",
    venue: "Seminar Hall B",
    coordinator: "Prof. Sunita Rao",
    description: "Hands-on coding with vector databases, LangChain, and embedding pipelines."
  },
  {
    customId: "sch-13",
    eventId: "evt-104",
    eventName: "Tarangini 2026: Annual Cultural Fest",
    activity: "Battle of the Bands (Rock & Fusion)",
    date: "2026-12-08",
    startTime: "04:30 PM",
    endTime: "07:30 PM",
    venue: "Open Air Amphitheatre",
    coordinator: "Kavya Menon",
    description: "Top 8 collegiate bands competing for the Golden Plectrum award."
  },
  {
    customId: "sch-14",
    eventId: "evt-104",
    eventName: "Tarangini 2026: Annual Cultural Fest",
    activity: "Bollywood & Hip-Hop Group Dance Finals",
    date: "2026-12-09",
    startTime: "05:00 PM",
    endTime: "08:30 PM",
    venue: "Open Air Amphitheatre",
    coordinator: "Cultural Secretary",
    description: "High-octane group dance performances with dynamic stage lighting."
  },
  {
    customId: "sch-15",
    eventId: "evt-105",
    eventName: "Khelotsav: Inter-College Sports Championship",
    activity: "Inter-College Football Grand Finale",
    date: "2026-12-20",
    startTime: "03:30 PM",
    endTime: "05:15 PM",
    venue: "College Main Football Ground",
    coordinator: "Harsh Vardhan",
    description: "Championship final match followed by trophy presentation."
  }
];

export const seedAnnouncements = [
  {
    customId: "ann-1",
    title: "TechFest 2026 Hackathon Room Allocation Released",
    message: "All registered coding and robotics teams must report to CS Block Lab 3 & 4 by 08:30 AM on 15th Nov for ID verification and Wi-Fi credential collection.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    postedBy: "Dr. Rajesh Verma (Lead Organizer)",
    date: "2026-10-24",
    priority: "Urgent",
    audience: "All Participants"
  },
  {
    customId: "ann-2",
    title: "Pre-requisite Setup Guide for AI Masterclass",
    message: "Please download the Jupyter notebooks from the event portal and test your HuggingFace API key tokens before entering Seminar Hall B.",
    eventId: "evt-103",
    eventName: "AI Innovation & LLM Masterclass",
    postedBy: "Prof. Sunita Rao",
    date: "2026-10-23",
    priority: "Important",
    audience: "Students"
  },
  {
    customId: "ann-3",
    title: "Volunteer Briefing Meeting for Cultural Fest",
    message: "Mandatory volunteer dry-run scheduled tomorrow at 04:30 PM in Room 102. T-shirts, ID lanyards, and walkie-talkies will be assigned.",
    eventId: "evt-104",
    eventName: "Tarangini 2026 Cultural Fest",
    postedBy: "Student Council Convener",
    date: "2026-10-22",
    priority: "Urgent",
    audience: "Volunteers"
  },
  {
    customId: "ann-4",
    title: "Khelotsav 2026 Fixtures & Schedule Published",
    message: "The official match fixtures for Cricket, Football, and Badminton have been uploaded to the Sports tab. Captains must report 30 mins before toss.",
    eventId: "evt-105",
    eventName: "Khelotsav Sports Championship",
    postedBy: "Dept. of Physical Education",
    date: "2026-10-21",
    priority: "Normal",
    audience: "All Participants"
  },
  {
    customId: "ann-5",
    title: "Cash Prize Pool Boosted to ₹1,50,000 for CodeSprint Hackathon",
    message: "Thanks to our prime industry sponsor CloudEdge Technologies, the total prize pool has been elevated with special category awards for Best UI/UX and Best AI integration.",
    eventId: "evt-102",
    eventName: "CodeSprint National Hackathon",
    postedBy: "IEDC Convener",
    date: "2026-10-20",
    priority: "Important",
    audience: "All Participants"
  },
  {
    customId: "ann-6",
    title: "Photography Submission Deadline Extended by 2 Days",
    message: "Owing to multiple student requests from the Department of Architecture, the deadline to upload high-resolution entries for Drishti is now Nov 17.",
    eventId: "evt-107",
    eventName: "Drishti Photography Contest",
    postedBy: "Photography Club President",
    date: "2026-10-19",
    priority: "Normal",
    audience: "Students"
  },
  {
    customId: "ann-7",
    title: "Parking and Traffic Advisory for Annual Day",
    message: "North gate entry will be reserved strictly for VIP vehicles and ambulance emergency clearance. Students are advised to park in West Quadrangle.",
    eventId: "evt-104",
    eventName: "Tarangini 2026 Cultural Fest",
    postedBy: "Campus Security Division",
    date: "2026-10-18",
    priority: "Important",
    audience: "All Participants"
  },
  {
    customId: "ann-8",
    title: "Volunteer Roster & Duty Shifts Uploaded",
    message: "Volunteers assigned to Stage Management and AV operations please check the updated shift timelines in your portal dashboard.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    postedBy: "Rohan Gupta (Volunteer Coordinator)",
    date: "2026-10-17",
    priority: "Normal",
    audience: "Volunteers"
  },
  {
    customId: "ann-9",
    title: "Food Stall & Refreshment Token Collection",
    message: "Registered external college delegates can collect their lunch wristbands from Desk 3 near the Central Canteen between 11 AM - 1 PM.",
    eventId: "evt-101",
    eventName: "TechFest 2026",
    postedBy: "Hospitality Team",
    date: "2026-10-16",
    priority: "Normal",
    audience: "All Participants"
  },
  {
    customId: "ann-10",
    title: "CyberShield CTF Platform Registration Open",
    message: "Flag capture server links and individual team tokens have been dispatched to the registered team lead email addresses.",
    eventId: "evt-108",
    eventName: "CyberShield Conclave",
    postedBy: "Cyber Security Group",
    date: "2026-10-15",
    priority: "Important",
    audience: "Students"
  }
];

export const seedRegistrations = seedParticipants;
